### ISSUE TITLE
[Bug]: Document the different behaviour of active tab and hidden tab when using Data module

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/teal#1303]
### What happened?

There is a different behaviour of data flow in modules when using transform during init.
The transform module server seems to be called for every module. But, shiny can trigger `reactive` values differently based on the shown/hidden state of the module. This can causing different behaviour for the active tab and hidden tab. It would be best to showcase this in the vignette about teal data module creation.

In the following example you can see that we have two `teal_modules` that are identical. However, we get a validation error in second module which is hidden and the first module works fine.

```r
devtools::load_all("teal")

my_transformers <- list(
  teal_transform_module(
    label = "Keep first 6 from IRIS",
    ui = function(id) {
      ns <- NS(id)
      div(
        checkboxInput(ns("check"), label = "Toggle `head(iris)`"),
      )
    },
    server = function(id, data) {
      moduleServer(id, function(input, output, session) {
        eventReactive(input$check, {
          print("Check triggered")
          req(data())
          if (input$check) {
            within(data(), iris <- head(iris, 6))
          } else {
            data()
          }
        })
      })
    }
  )
)

data <- teal_data(iris = iris)
app <- init(
  data = data,
  modules = modules(
    example_module("Module with transformations 1", transformers = my_transformers),
    example_module("Module with transformations 2", transformers = my_transformers)
  )
)

shinyApp(app$ui, app$server)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by averissimo** [comment]
@vedhav can you confirm that this was fixed in #1253 ?

**Comment by vedhav** [comment]
This issue persists. When I run the app mentioned in this issue I get the error message in the second tab that could have been avoided.

<img width="1468" alt="Screenshot 2024-08-13 at 2 56 27 PM" src="https://github.com/user-attachments/assets/cb543e22-6b1b-4244-b0f3-d08efb0181c9">
<img width="1470" alt="Screenshot 2024-08-13 at 2 56 33 PM" src="https://github.com/user-attachments/assets/8e58d79d-f35e-4ea1-b6f5-2f2908cc16cd">

**Comment by averissimo** [comment]
_TL;DR_: This is a consequence of our transform design that penalizes transform modules that are not reactive to `data()`

Action: Do you think we can detect or mitigate it?

Context:

What happens here is that the data is changing, but the `eventReactive` is not sensitive to that change.

The app developer should either:

1. use `eventReactive(list(input$check, data()), { ... }`
    - note the `data()` in the `eventExpr` argument
2. or totally avoid `eventReactive(...)`

In the example below you can see that in the first tab the first transformers don't affect the result as it's only reactive to `input$check`

[Screencast from 2024-08-13 15-17-20.webm](https://github.com/user-attachments/assets/c2c86504-9b66-444e-8482-cfc0d9d09f24)

```r

options(
  teal.log_level = "DEBUG",
  teal.show_js_log = TRUE,
  # teal.bs_theme = bslib::bs_theme(version = 5),
  shiny.bookmarkStore = "server"
)

devtools::load_all("teal")


my_transformers <- list(
  teal_transform_module(
    label = "Keep first 10 from IRIS",
    ui = function(id) {
      ns <- NS(id)
      div(
        checkboxInput(ns("check"), label = "Toggle keep only first 10 rows?"),
      )
    },
    server = function(id, data) {
      moduleServer(id, function(input, output, session) {
        result <- reactive({
          print(glue::glue("Check triggered {session$ns('id')} { input$check %||% '(null)' }"))
          req(data())
          if (input$check) {
            within(data(), iris <- head(iris, 10))
          } else {
            data()
          }
        })
        
        result
      })
    }
  ),
  teal_transform_module(
    label = "Sepal.length negative?",
    ui = function(id) {
      ns <- NS(id)
      div(
        checkboxInput(ns("check"), label = "Negative Sepal.length?"),
      )
    },
    server = function(id, data) {
      moduleServer(id, function(input, output, session) {
        result <- reactive({
          print(glue::glue("Check triggered {session$ns('id')} { input$check %||% '(null)' }"))
          req(data())
          if (input$check) {
            within(data(), iris$Sepal.Length <- iris$Sepal.Length * -1)
          } else {
            data()
          }
        })
        
        result
      })
    }
  ),
  teal_transform_module(
    label = "Keep first 6 from IRIS",
    ui = function(id) {
      ns <- NS(id)
      div(
        checkboxInput(ns("check"), label = "Toggle `head(iris)`"),
      )
    },
    server = function(id, data) {
      moduleServer(id, function(input, output, session) {
        eventReactive(input$check, {
          print(glue::glue("Check triggered {session$ns('id')} { input$check %||% '(null)' }"))
          req(data())
          if (input$check) {
            within(data(), iris <- head(iris, 6))
          } else {
            data()
          }
        })
      })
    }
  )
)

my_transformers_good <- append(
  my_transformers[1:2],
  list(
    teal_transform_module(
      label = "Keep first 6 from IRIS (good)",
      ui = function(id) {
        ns <- NS(id)
        div(
          checkboxInput(ns("check"), label = "Toggle `head(iris)`"),
        )
      },
      server = function(id, data) {
        moduleServer(id, function(input, output, session) {
          eventReactive(list(input$check, data()), {
            print(glue::glue("Check triggered {session$ns('id')} { input$check %||% '(null)' }"))
            req(data())
            if (input$check) {
              within(data(), iris <- head(iris, 6))
            } else {
              data()
            }
          })
        })
      }
    )
  )
)

data <- teal_data(iris = iris)
app <- init(
  data = data,
  modules = modules(
    example_module("Module with transformations 1", transformers = my_transformers),
    example_module("Module with transformations 2", transformers = my_transformers_good)
  )
)

shinyApp(app$ui, app$server)
```

**Comment by vedhav** [comment]
Adding the general conclusion we had related to this issue.
In general, shiny behaves this way. When the UI is hidden some reactive values are not triggered and I don't think we would be able to initialize the values for some cases. So, it is best to recommend that the `teal_data_module` author to pass the `teal_data` object as `reactive` even when the module is hidden.
We should change the scope of this issue to: Add this behaviour in the vignette of the `teal_data_module` construction.

**Comment by gogonzo** [comment]
I have a feeling that something is missing. If at least one module (first one) performs properly, then maybe we can do something to enable the same behaviour to the second one. Like:
- delaying and triggering `srv_teal_module` until the module `is_active` (module can't be active if data is not loaded, because tabs are blocked)

**Comment by gogonzo** [comment]
@donyunardi PR is coming to resolve the root cause. @averissimo is taking care of it 💪
